import React from 'react'
import { CustomHead } from '@/components'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Script from 'next/script'
import { CLARITY_SCRIPT } from '@/constants'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <CustomHead />
      <Script id='ms-clarity' strategy='afterInteractive'>
        {CLARITY_SCRIPT}
      </Script>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
